### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by Speedy1991** [ddanier/fabdeploit#6]
__Behaviour:__
New release is created even the release build fails.

__Steps to reprocude:__
- Create a _requirements.txt_ for the _Virtualenv_ but without adding it to the commit.
- Run fab

Error on this lines (expected):
[localhost] run: /home/git/django_deploy/_env/bin/pip3 install -Ur "/home/git/django_deploy/requirements.txt"
[localhost] out: Could not open requirements file: [Errno 2] No such file or directory: '/home/git/django_deploy/requirements.txt'

Looking into the git tree the release is created even the build failed (unexpected):
<a href="https://ibb.co/nBr37Q"><img src="https://preview.ibb.co/gtms1k/gittree.png" alt="gittree" border="0"></a>

__Expected behaviour:__
No release

**Comment by ddanier** [comment]
This is the expected behavior. fabdeploit will create the release commit to prepare the upload. It will then push the commit to the server (at this point the commit MUST exist).

After the push is done fabdeploit will run all scripts necessary for running your application on the server. This may include setup of your virtualenv. If something fails here the commit is already done, as it was necessary for the upload to work.

**Comment by Speedy1991** [comment]
I see your point. Maybe adding/updating a hint in the commit message that the build failed would be a nice feature.
Checkout an older (and working) commit on the production server would be much easier that way.
E.g.: FAILED Deploying cb6xxx...

**Comment by ddanier** [comment]
As we create the commit before the upload the commit message is set way before the error occurs. So we cannot change the commit message without changing the commit sha1 and by this changing the commit history.

When I look at out own deployments errors like this only occur on the initial setup. These commits normally don't need to be checked out later on. I never ran into a situation where this behavior really was some kind of problem.

**Comment by Speedy1991** [comment]
Ok. Thanks for clarification.
